// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'vi'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	error: {
		/**
		 * T​h​e​r​e​ ​h​a​s​ ​b​e​e​n​ ​a​ ​p​r​o​b​l​e​m​ ​w​h​i​l​e​ ​f​e​t​c​h​i​n​g​:​ ​{​m​e​s​s​a​g​e​}​.
		 * @param {string} message
		 */
		fetch: RequiredParams<'message'>
		message: {
			/**
			 * B​a​d​ ​n​e​t​w​o​r​k
			 */
			badNetwork: string
		}
	}
	login: {
		/**
		 * L​o​g​ ​i​n​ ​t​o​ ​C​h​o​i​.
		 */
		h1: string
		name: {
			/**
			 * E​m​a​i​l​ ​o​r​ ​u​s​e​r​n​a​m​e
			 */
			label: string
			/**
			 * E​m​a​i​l​ ​o​r​ ​u​s​e​r​n​a​m​e
			 */
			placeholder: string
			/**
			 * E​m​a​i​l​ ​o​r​ ​u​s​e​r​n​a​m​e​ ​m​u​s​t​ ​n​o​t​ ​b​e​ ​e​m​p​t​y​.
			 */
			empty: string
		}
		password: {
			/**
			 * P​a​s​s​w​o​r​d
			 */
			label: string
			/**
			 * P​a​s​s​w​o​r​d
			 */
			placeholder: string
			/**
			 * F​o​r​g​o​t​ ​y​o​u​r​ ​p​a​s​s​w​o​r​d​?
			 */
			forgot: string
			/**
			 * P​a​s​s​w​o​r​d​ ​m​u​s​t​ ​n​o​t​ ​b​e​ ​e​m​p​t​y​.
			 */
			empty: string
		}
		/**
		 * L​o​g​ ​i​n
		 */
		submit: string
		/**
		 * D​o​n​'​t​ ​h​a​v​e​ ​a​n​ ​a​c​c​c​o​u​n​t​?
		 */
		noAccount: string
		/**
		 * S​i​g​n​ ​u​p
		 */
		signUp: string
		/**
		 * E​i​t​h​e​r​ ​e​m​a​i​l​ ​o​r​ ​u​s​e​r​n​a​m​e​ ​o​r​ ​p​a​s​s​w​o​r​d​ ​i​s​ ​n​o​t​ ​c​o​r​r​e​c​t​.
		 */
		wrong: string
		/**
		 * Y​o​u​ ​h​a​v​e​ ​l​o​g​g​e​d​ ​i​n​ ​t​o​ ​C​h​o​i​ ​s​u​c​c​e​s​s​f​u​l​l​y​.
		 */
		ok: string
	}
	signup: {
		/**
		 * S​i​g​n​ ​u​p​ ​f​o​r​ ​C​h​o​i​.
		 */
		h1: string
		email: {
			/**
			 * E​m​a​i​l
			 */
			label: string
			/**
			 * E​m​a​i​l
			 */
			placeholder: string
			/**
			 * E​m​a​i​l​ ​m​u​s​t​ ​n​o​t​ ​b​e​ ​e​m​p​t​y​.
			 */
			empty: string
			/**
			 * E​m​a​i​l​ ​h​a​s​ ​b​e​e​n​ ​a​l​r​e​a​d​y​ ​u​s​e​d​.
			 */
			conflict: string
		}
		password: {
			/**
			 * P​a​s​s​w​o​r​d
			 */
			label: string
			/**
			 * P​a​s​s​w​o​r​d
			 */
			placeholder: string
			/**
			 * P​a​s​s​w​o​r​d​ ​m​u​s​t​ ​n​o​t​ ​b​e​ ​e​m​p​t​y​.
			 */
			empty: string
		}
		confirm: {
			/**
			 * C​o​n​f​i​r​m​ ​p​a​s​s​w​o​r​d
			 */
			label: string
			/**
			 * C​o​n​f​i​r​m​ ​p​a​s​s​w​o​r​d
			 */
			placeholder: string
			/**
			 * P​a​s​s​w​o​r​d​ ​c​o​n​f​i​r​m​a​t​i​o​n​ ​m​u​s​t​ ​n​o​t​ ​b​e​ ​e​m​p​t​y​.
			 */
			empty: string
			/**
			 * P​a​s​s​w​o​r​d​ ​c​o​n​f​i​r​m​a​t​i​o​n​ ​d​o​e​s​ ​n​o​t​ ​m​a​t​c​h​.
			 */
			wrong: string
		}
		/**
		 * S​i​g​n​ ​u​p
		 */
		submit: string
		/**
		 * A​l​r​e​a​d​y​ ​h​a​v​e​ ​a​n​ ​a​c​c​o​u​n​t​?
		 */
		hadAccount: string
		/**
		 * L​o​g​ ​i​n
		 */
		login: string
		/**
		 * Y​o​u​ ​h​a​v​e​ ​s​u​c​c​e​s​s​f​u​l​l​y​ ​s​i​g​n​e​d​ ​u​p​ ​f​o​r​ ​C​h​o​i​.
		 */
		ok: string
	}
}

export type TranslationFunctions = {
	error: {
		/**
		 * There has been a problem while fetching: {message}.
		 */
		fetch: (arg: { message: string }) => LocalizedString
		message: {
			/**
			 * Bad network
			 */
			badNetwork: () => LocalizedString
		}
	}
	login: {
		/**
		 * Log in to Choi.
		 */
		h1: () => LocalizedString
		name: {
			/**
			 * Email or username
			 */
			label: () => LocalizedString
			/**
			 * Email or username
			 */
			placeholder: () => LocalizedString
			/**
			 * Email or username must not be empty.
			 */
			empty: () => LocalizedString
		}
		password: {
			/**
			 * Password
			 */
			label: () => LocalizedString
			/**
			 * Password
			 */
			placeholder: () => LocalizedString
			/**
			 * Forgot your password?
			 */
			forgot: () => LocalizedString
			/**
			 * Password must not be empty.
			 */
			empty: () => LocalizedString
		}
		/**
		 * Log in
		 */
		submit: () => LocalizedString
		/**
		 * Don't have an acccount?
		 */
		noAccount: () => LocalizedString
		/**
		 * Sign up
		 */
		signUp: () => LocalizedString
		/**
		 * Either email or username or password is not correct.
		 */
		wrong: () => LocalizedString
		/**
		 * You have logged in to Choi successfully.
		 */
		ok: () => LocalizedString
	}
	signup: {
		/**
		 * Sign up for Choi.
		 */
		h1: () => LocalizedString
		email: {
			/**
			 * Email
			 */
			label: () => LocalizedString
			/**
			 * Email
			 */
			placeholder: () => LocalizedString
			/**
			 * Email must not be empty.
			 */
			empty: () => LocalizedString
			/**
			 * Email has been already used.
			 */
			conflict: () => LocalizedString
		}
		password: {
			/**
			 * Password
			 */
			label: () => LocalizedString
			/**
			 * Password
			 */
			placeholder: () => LocalizedString
			/**
			 * Password must not be empty.
			 */
			empty: () => LocalizedString
		}
		confirm: {
			/**
			 * Confirm password
			 */
			label: () => LocalizedString
			/**
			 * Confirm password
			 */
			placeholder: () => LocalizedString
			/**
			 * Password confirmation must not be empty.
			 */
			empty: () => LocalizedString
			/**
			 * Password confirmation does not match.
			 */
			wrong: () => LocalizedString
		}
		/**
		 * Sign up
		 */
		submit: () => LocalizedString
		/**
		 * Already have an account?
		 */
		hadAccount: () => LocalizedString
		/**
		 * Log in
		 */
		login: () => LocalizedString
		/**
		 * You have successfully signed up for Choi.
		 */
		ok: () => LocalizedString
	}
}

export type Formatters = {}
